main:
  - name: "Features"
    url: "/#features"
    weight: 1

  - name: "How it works"
    url: "/#how-it-works"
    weight: 2

  - name: "Pricing"
    url: "/#pricing"
    weight: 3

  - name: "Blog"
    url: "/post"
    weight: 4

buttons:
  - name: "Get early access"
    url: "/#early-access"
    weight: 1

footer:
  - name: "Features"
    url: "/#features"
    weight: 1

  - name: "How it works"
    url: "/#how-it-works"
    weight: 2

  - name: "Pricing"
    url: "/#pricing"
    weight: 3

  - name: "Blog"
    url: "/post"
    weight: 4
